-- Run as ACCOUNTADMIN/USERADMIN. Registers the public key matching rsa_key.p8
-- Expected fingerprint after running DESC USER: SHA256:/ekCZt1JVK/NQFMWW69E5mvY0BqOzbB0ZaUKox2YFGQ=

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS EVIDENCE_WH WAREHOUSE_SIZE=XSMALL AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;
CREATE DATABASE IF NOT EXISTS EVIDENCE_DB;
CREATE SCHEMA IF NOT EXISTS EVIDENCE_DB.PUBLIC;
CREATE ROLE IF NOT EXISTS EVIDENCE_APP_ROLE;
GRANT USAGE ON WAREHOUSE EVIDENCE_WH TO ROLE EVIDENCE_APP_ROLE;
GRANT USAGE ON DATABASE EVIDENCE_DB TO ROLE EVIDENCE_APP_ROLE;
GRANT USAGE ON SCHEMA EVIDENCE_DB.PUBLIC TO ROLE EVIDENCE_APP_ROLE;
GRANT CREATE TABLE ON SCHEMA EVIDENCE_DB.PUBLIC TO ROLE EVIDENCE_APP_ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON FUTURE TABLES IN SCHEMA EVIDENCE_DB.PUBLIC TO ROLE EVIDENCE_APP_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA EVIDENCE_DB.PUBLIC TO ROLE EVIDENCE_APP_ROLE;
GRANT CREATE VIEW ON SCHEMA EVIDENCE_DB.PUBLIC TO ROLE EVIDENCE_APP_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA EVIDENCE_DB.PUBLIC TO ROLE EVIDENCE_APP_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA EVIDENCE_DB.PUBLIC TO ROLE EVIDENCE_APP_ROLE;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE EVIDENCE_APP_ROLE;

CREATE USER IF NOT EXISTS EVIDENCE_SVC DEFAULT_ROLE=EVIDENCE_APP_ROLE DEFAULT_WAREHOUSE=EVIDENCE_WH;
GRANT ROLE EVIDENCE_APP_ROLE TO USER EVIDENCE_SVC;

ALTER USER EVIDENCE_SVC SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs81WVCp8HuJpcvsq/X9DNUBku+dVqI+Xtd+4qi7znxoTBwHseXQW3WxL7wayq9ue8cqATCClOvdUnrxeEVMU+WS+bBsFZSMcbqqSyzhNA++xcrkMqXnn+XRlR2Kt0nYtdStbqBcI4Kdc6X6kYlEWeknYKTqkEFHKnzGtcPY47SVgPeJOAxRm/RyQKbESspPnm3mXdMO5UQB9jym4H+kGPpOddfuGWMpxy1b8JwaCwLaGx3hgnUVmvhnXdAmKPmmrAAsOoRypiDrtUP3WXNGOVfBmSmUCDB12d/MLHviXQ+VwKeOtATA/E86iwYeMgHe54PNIv9H42FfP0H1bbKpabQIDAQAB';

DESC USER EVIDENCE_SVC;
